#!/usr/bin/bash
# get data from a specific pokemon on the list and save the data in their specific file


# configuration
POKEMONS_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
URL="https://pokeapi.co/api/v2/pokemon/"

http_status=$(curl -I https://pokeapi.co/api/v2/pokemon/ | sed -n '1p' | awk '{print $2}')

mkdir -p pokemon_data
if curl -s "${URL}"
then
    echo "Success"
    for pokemon in "${POKEMONS_LIST[@]}";
    do
        echo "Successful request: processing request for ${pokemon}"
        curl -s "https://pokeapi.co/api/v2/pokemon/${pokemon}"| jq > pokemon_data/"${pokemon}".json
        sleep 1
    done
else 
    echo "failure"
fi
